build_from:
  aarch64: 'ghcr.io/home-assistant/aarch64-base:3.22'
  amd64: 'ghcr.io/home-assistant/amd64-base:3.22'
labels:
  org.opencontainers.image.title: 'Home Assistant Add-on: n8n'
  org.opencontainers.image.description:
    Flexible AI workflow automation for technical teams. Build with the
    precision of code or the speed of drag-n-drop. Host with on-prem control or
    in-the-cloud convenience. n8n gives you more freedom to implement multi-step
    AI agents and integrate apps than any other tool.
  org.opencontainers.image.source: 'https://github.com/kanso-org/hassio-addons'
  org.opencontainers.image.licenses: 'MIT'
