build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bookworm"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bookworm"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:bookworm"
labels:
  org.opencontainers.image.title: 'Home Assistant Add-on: Hyperion'
  org.opencontainers.image.description:
    Hyperion is an open source (MIT) Bias or Ambient Lighting implementation for
    GNU/Linux, macOS and Windows, which you might know from TV manufacturers. It
    supports many LED devices and video grabbers. In simple words, this software
    dynamically processes input video signal (using for example current video
    framebuffer), and converts it into signal to steer ambient light (using for
    example LED strips controlled over USB device).
  org.opencontainers.image.source: 'https://github.com/kanso-org/hassio-addons'
  org.opencontainers.image.licenses: 'MIT'
